---
skillMetadata:
  sections:
    - name: Authenticating
      fields:
        - name: token
          type: password
          label: Trello API token
          value: ""
          placeholder: ...paste here...
        - name: key
          type: password
          label: Trello API key
          value: ""
          placeholder: ...paste here...
        - name: default_board_id
          type: text
          label: Default board
          value: ""
          placeholder: ...paste here...
    # - name: Login << Name of another section
    #   fields:
    #     - type: label
    #       label: Just a little bit of extra info for the user to understand following settings
    #     - name: username
    #       type: text
    #       label: Username
    #       value: ""
    #     - name: password
    #       type: password
    #       label: Password
    #       value: ""
